const recipes = [
['Petit-déjeuner','Fromage blanc 0% + flocons d’avoine + fruits rouges',520,38,58,8,'300 g de fromage blanc 0%, 60 g de flocons d’avoine, 150 g de fruits rouges','Mélanger tous les ingrédients dans un bol.'],
['Petit-déjeuner','Omelette pommes de terre',610,36,55,18,'3 œufs, 250 g de pommes de terre, épices','Cuire les pommes de terre à l’airfryer, puis préparer l’omelette.'],
['Petit-déjeuner','Skyr banane beurre de cacahuète',540,40,52,14,'300 g de skyr, 1 banane, 15 g de beurre de cacahuète','Couper la banane puis mélanger tous les ingrédients.'],
['Petit-déjeuner','Pancakes avoine',560,35,60,12,'Flocons d’avoine, œufs, fromage blanc 0%','Mélanger la pâte et cuire les pancakes à la poêle.'],
['Petit-déjeuner','Toast complet dinde',500,34,45,12,'Pain complet, dinde, fromage blanc 0%','Toaster le pain puis assembler.'],
['Petit-déjeuner','Bowl pomme cannelle',530,36,62,5,'Fromage blanc 0%, flocons d’avoine, pomme','Couper la pomme, ajouter une pincée de cannelle et mélanger.'],
['Petit-déjeuner','Wrap œufs brouillés',580,37,50,16,'Wrap complet, œufs, dinde','Brouiller les œufs à la poêle puis garnir le wrap.'],
['Petit-déjeuner','Smoothie protéiné',510,42,48,8,'Fromage blanc 0%, banane, flocons d’avoine','Mixer jusqu’à obtenir une texture lisse.'],
['Déjeuner','Poulet paprika & pommes de terre',760,58,70,18,'250 g de poulet, 400 g de pommes de terre, paprika','Cuire à l’airfryer à 200 °C pendant 25 à 30 minutes.'],
['Déjeuner','Steak 5% & potatoes',740,48,68,20,'200 g de steak haché 5%, 400 g de pommes de terre','Cuire les pommes de terre à l’airfryer et le steak selon votre goût.'],
['Déjeuner','Poulet curry léger & riz',780,60,75,15,'Poulet, riz, curry, skyr','Cuire à la poêle et ajouter le skyr hors du feu pour une sauce crémeuse.'],
['Déjeuner','Boulettes 5% tomate',730,52,62,18,'Viande hachée 5%, coulis de tomate, pâtes complètes','Former les boulettes, les dorer à la poêle puis ajouter le coulis.'],
['Déjeuner','Chili léger',770,55,65,16,'Viande hachée 5%, haricots rouges','Faire revenir la viande, ajouter les haricots et laisser mijoter.'],
['Déjeuner','Poulet moutarde',750,60,60,18,'Poulet, fromage blanc 0%, moutarde, pommes de terre','Cuire le poulet et les pommes de terre à l’airfryer. Mélanger la sauce à part.'],
['Déjeuner','Burger healthy',720,50,58,20,'Pain complet, viande hachée 5%, cheddar allégé','Assembler et réchauffer quelques minutes à l’airfryer.'],
['Déjeuner','Émincé de poulet & légumes',700,58,45,18,'Poulet, légumes au choix','Émincer puis faire revenir le tout à la poêle avec des épices.'],
['Déjeuner','Pommes de terre grenaille & dinde',730,54,68,12,'Dinde, pommes de terre grenaille','Assaisonner puis cuire à l’airfryer.'],
['Déjeuner','Tacos healthy',760,55,65,18,'Galette complète, viande hachée 5%, fromage allégé','Garnir, replier puis faire dorer à l’airfryer.'],
['Déjeuner','Saumon & pommes de terre',790,45,60,28,'Saumon, pommes de terre','Assaisonner puis cuire à l’airfryer.'],
['Dîner','Poulet paprika & pommes de terre',760,58,70,18,'250 g de poulet, 400 g de pommes de terre, paprika','Cuire à l’airfryer à 200 °C pendant 25 à 30 minutes.'],
['Dîner','Steak 5% & potatoes',740,48,68,20,'200 g de steak haché 5%, 400 g de pommes de terre','Cuire les pommes de terre à l’airfryer et le steak selon votre goût.'],
['Dîner','Poulet curry léger & riz',780,60,75,15,'Poulet, riz, curry, skyr','Cuire à la poêle et ajouter le skyr hors du feu.'],
['Dîner','Boulettes 5% tomate',730,52,62,18,'Viande hachée 5%, coulis de tomate, pâtes complètes','Former les boulettes, les dorer puis ajouter le coulis.'],
['Dîner','Chili léger',770,55,65,16,'Viande hachée 5%, haricots rouges','Faire revenir la viande, ajouter les haricots et laisser mijoter.'],
['Dîner','Poulet moutarde',750,60,60,18,'Poulet, fromage blanc 0%, moutarde, pommes de terre','Cuire à l’airfryer et servir avec la sauce.'],
['Dîner','Burger healthy',720,50,58,20,'Pain complet, viande hachée 5%, cheddar allégé','Assembler et faire dorer quelques minutes à l’airfryer.'],
['Collation','Fromage blanc 0% + miel + kiwi',280,27,28,1,'300 g de fromage blanc 0%, 10 g de miel, 1 kiwi','Couper le kiwi puis assembler dans un bol.'],
['Collation','Skyr + pomme',220,22,24,0,'250 g de skyr, 1 pomme','Couper la pomme et servir avec le skyr.'],
['Collation','Shake protéiné + banane',250,30,24,2,'Whey, banane','Mixer ou secouer la whey, puis accompagner d’une banane.'],
['Collation','Galettes de riz + dinde',260,22,26,3,'3 galettes de riz, 80 g de dinde','Déposer la dinde sur les galettes et déguster.']
].map((r,id)=>({id,meal:r[0],name:r[1],kcal:r[2],protein:r[3],carbs:r[4],fat:r[5],ingredients:r[6],prep:r[7]}));
const photoByName={
'Fromage blanc 0% + flocons d’avoine + fruits rouges':'assets/recipes/fromage-blanc-fruits-rouges.png','Omelette pommes de terre':'assets/recipes/omelette-pommes-terre.png','Skyr banane beurre de cacahuète':'assets/recipes/skyr-banane.png','Pancakes avoine':'assets/recipes/pancakes-avoine.png','Toast complet dinde':'assets/recipes/toast-dinde.png','Bowl pomme cannelle':'assets/recipes/bowl-pomme.png','Wrap œufs brouillés':'assets/recipes/wrap-oeufs.png','Smoothie protéiné':'assets/recipes/smoothie-proteine.png','Poulet paprika & pommes de terre':'assets/recipes/poulet-paprika.png','Steak 5% & potatoes':'assets/recipes/steak-potatoes.png','Poulet curry léger & riz':'assets/recipes/poulet-curry.png','Boulettes 5% tomate':'assets/recipes/boulettes-tomate.png','Chili léger':'assets/recipes/chili.png','Poulet moutarde':'assets/recipes/poulet-moutarde.png','Burger healthy':'assets/recipes/burger-healthy.png','Émincé de poulet & légumes':'assets/recipes/poulet-legumes.png','Pommes de terre grenaille & dinde':'assets/recipes/dinde-grenailles.png','Tacos healthy':'assets/recipes/tacos-healthy.png','Saumon & pommes de terre':'assets/recipes/saumon-pommes-terre.png','Fromage blanc 0% + miel + kiwi':'assets/recipes/fromage-blanc-kiwi.png','Skyr + pomme':'assets/recipes/skyr-pomme.png','Shake protéiné + banane':'assets/recipes/shake-banane.png','Galettes de riz + dinde':'assets/recipes/galettes-riz-dinde.png'};
const instructions={
'Fromage blanc 0% + flocons d’avoine + fruits rouges':['Verser le fromage blanc dans un grand bol.','Ajouter les flocons d’avoine et mélanger pour bien les enrober.','Répartir les fruits rouges sur le dessus. Laisser reposer 5 minutes pour une texture plus fondante.'],
'Omelette pommes de terre':['Préchauffer l’airfryer à 200 °C. Couper les pommes de terre en petits dés réguliers.','Assaisonner les dés et les cuire 18 à 22 minutes, en remuant à mi-cuisson.','Battre les œufs avec les épices dans un bol.','Verser dans une poêle chaude, ajouter les pommes de terre et cuire à feu doux jusqu’à la texture souhaitée.'],
'Skyr banane beurre de cacahuète':['Verser le skyr dans un bol et le détendre avec une cuillère.','Couper la banane en rondelles et les disposer sur le skyr.','Ajouter le beurre de cacahuète en filet. Mélanger au moment de déguster.'],
'Pancakes avoine':['Mixer ou mélanger les flocons d’avoine, les œufs et le fromage blanc jusqu’à obtenir une pâte homogène.','Laisser reposer la pâte 5 minutes.','Déposer de petites louches dans une poêle antiadhésive chaude.','Retourner quand des bulles apparaissent et cuire encore 1 à 2 minutes.'],
'Toast complet dinde':['Faire griller le pain complet jusqu’à ce qu’il soit légèrement croustillant.','Étaler le fromage blanc sur chaque tranche.','Ajouter la dinde, poivrer et refermer ou servir en tartines.'],
'Bowl pomme cannelle':['Verser le fromage blanc et les flocons d’avoine dans un bol.','Couper la pomme en dés fins, avec ou sans la peau.','Ajouter la pomme et une généreuse pincée de cannelle.','Mélanger puis laisser reposer 5 minutes avant de servir.'],
'Wrap œufs brouillés':['Battre les œufs puis les cuire à feu doux en remuant régulièrement.','Réchauffer le wrap quelques secondes dans une poêle sèche.','Déposer la dinde puis les œufs brouillés au centre.','Rabattre les côtés, rouler fermement et faire dorer 1 minute sur chaque face.'],
'Smoothie protéiné':['Couper la banane en morceaux.','Placer le fromage blanc, la banane et les flocons d’avoine dans un blender.','Mixer 30 à 45 secondes. Ajouter un peu d’eau si nécessaire pour ajuster la texture.','Servir immédiatement.'],
'Poulet paprika & pommes de terre':['Préchauffer l’airfryer à 200 °C. Couper les pommes de terre en quartiers et le poulet en morceaux.','Assaisonner généreusement avec le paprika, du sel et du poivre.','Cuire les pommes de terre 10 minutes seules, puis ajouter le poulet.','Poursuivre 15 à 20 minutes en remuant à mi-cuisson. Vérifier que le poulet est bien cuit à cœur.'],
'Steak 5% & potatoes':['Préchauffer l’airfryer à 200 °C et couper les pommes de terre en quartiers.','Assaisonner puis cuire 22 à 28 minutes, en secouant le panier à mi-cuisson.','Cuire le steak dans une poêle bien chaude, selon la cuisson désirée.','Laisser reposer le steak 2 minutes puis servir avec les potatoes.'],
'Poulet curry léger & riz':['Cuire le riz selon les indications du paquet.','Découper le poulet et le faire dorer dans une poêle chaude.','Ajouter le curry et un petit fond d’eau, puis laisser cuire à feu doux.','Retirer du feu, incorporer le skyr et mélanger. Servir aussitôt avec le riz.'],
'Boulettes 5% tomate':['Former des boulettes de taille régulière avec la viande hachée assaisonnée.','Les faire dorer sur toutes les faces dans une poêle antiadhésive.','Ajouter le coulis de tomate et laisser mijoter 10 à 12 minutes.','Cuire les pâtes complètes séparément puis servir avec les boulettes et la sauce.'],
'Chili léger':['Faire revenir la viande hachée dans une casserole chaude en l’émiettant.','Rincer et égoutter les haricots rouges, puis les ajouter.','Assaisonner selon le goût et ajouter un petit fond d’eau si nécessaire.','Couvrir et laisser mijoter 15 minutes à feu doux.'],
'Poulet moutarde':['Couper les pommes de terre et les cuire à l’airfryer à 200 °C pendant 22 à 28 minutes.','Découper et assaisonner le poulet, puis le cuire à la poêle ou à l’airfryer jusqu’à cuisson complète.','Mélanger le fromage blanc et la moutarde dans un bol.','Servir le poulet et les pommes de terre avec la sauce froide ou légèrement tiédie.'],
'Burger healthy':['Cuire le steak haché dans une poêle bien chaude.','Ouvrir le pain complet et déposer le steak puis le cheddar allégé.','Refermer et passer 3 à 4 minutes à l’airfryer à 180 °C.','Servir dès que le fromage est fondu.'],
'Émincé de poulet & légumes':['Découper le poulet en fines lanières et les légumes en morceaux réguliers.','Saisir le poulet dans une grande poêle chaude.','Ajouter les légumes et les épices de votre choix.','Cuire 8 à 12 minutes en remuant, jusqu’à ce que le poulet soit cuit et les légumes encore légèrement croquants.'],
'Pommes de terre grenaille & dinde':['Préchauffer l’airfryer à 195 °C. Couper les plus grosses pommes de terre en deux.','Assaisonner les grenailles puis les cuire 15 minutes.','Ajouter la dinde découpée en lanières et mélanger.','Poursuivre la cuisson 10 à 12 minutes, en remuant une fois.'],
'Tacos healthy':['Faire revenir la viande hachée assaisonnée dans une poêle.','Déposer la viande et le fromage allégé au centre de la galette.','Rabattre les quatre côtés pour former un rectangle fermé.','Faire dorer à l’airfryer à 190 °C pendant 6 à 8 minutes, pliure vers le bas.'],
'Saumon & pommes de terre':['Préchauffer l’airfryer à 195 °C. Couper et assaisonner les pommes de terre.','Cuire les pommes de terre seules pendant 15 minutes.','Ajouter le saumon assaisonné dans le panier sans le superposer.','Poursuivre 8 à 12 minutes selon l’épaisseur du pavé, puis servir immédiatement.'],
'Fromage blanc 0% + miel + kiwi':['Verser le fromage blanc dans un bol.','Éplucher le kiwi et le couper en dés ou en rondelles.','Disposer le kiwi sur le fromage blanc puis ajouter le miel en filet.'],
'Skyr + pomme':['Verser le skyr dans un bol.','Laver puis couper la pomme en fines lamelles ou en dés.','Ajouter la pomme au skyr et déguster bien frais.'],
'Shake protéiné + banane':['Verser la whey et la quantité d’eau adaptée dans un shaker.','Secouer vivement pendant 20 à 30 secondes, jusqu’à disparition des grumeaux.','Servir avec la banane, entière ou coupée en rondelles.'],
'Galettes de riz + dinde':['Disposer les galettes de riz sur une assiette.','Répartir les tranches de dinde sur les galettes.','Poivrer ou ajouter des herbes selon le goût, puis servir immédiatement.']};
const guides=[['≈ 2 900 kcal','Un objectif quotidien à ajuster selon ton évolution.','◒'],['180–220 g','de protéines par jour pour soutenir la satiété.','◇'],['Des légumes','à chaque déjeuner et dîner.','♧'],['L’airfryer','pour une cuisson simple avec moins de matière grasse.','♨'],['Bien s’hydrater','eau, café ou thé sans sucre, sodas zéro.','⌁'],['Varier les épices','pour garder le plaisir et éviter la monotonie.','✦'],['Les aliments stars','Pommes de terre, poulet, viande 5 %, fromage blanc, skyr, riz et légumes.','★']];
const limits=[['Sodas sucrés','Très caloriques, peu rassasiants'],['Sirops','Du sucre liquide'],['Bonbons','Très forte densité calorique'],['Viennoiseries','Sucres et graisses'],['Fast-food fréquent','Calories élevées'],['Fritures','Beaucoup d’huile'],['Chips','Très caloriques'],['Céréales sucrées','Peu rassasiantes'],['Alcool','Calories et baisse du contrôle alimentaire'],['Jus de fruits industriels','Sucres rapides'],['Sauces industrielles','Sucres et huiles ajoutés'],['Pâtisseries','Très riches en calories'],['Boissons énergétiques sucrées','Teneur élevée en sucre'],['Pain de mie brioché','Faible satiété'],['Glaces industrielles','Sucre et graisse']];
const icons={'Petit-déjeuner':'☀','Déjeuner':'♨','Dîner':'☾','Collation':'◒'}, colors={'Petit-déjeuner':['#ead7b4','#d8a84f'],'Déjeuner':['#d7e2ce','#789369'],'Dîner':['#d6d8cf','#6c7d72'],'Collation':['#efd8c8','#cb7956']};
let active='Tous', query='', favorites=new Set(JSON.parse(localStorage.getItem('meal-favorites')||'[]'));
const grid=document.querySelector('#recipe-grid'), modal=document.querySelector('#recipe-modal');
document.querySelector('#guides').innerHTML=guides.map(g=>`<article class="guide"><span class="guide-icon">${g[2]}</span><h3>${g[0]}</h3><p>${g[1]}</p></article>`).join('');
document.querySelector('#limit-list').innerHTML=limits.map(x=>`<div class="limit-item"><span>○</span><div><strong>${x[0]}</strong><small>${x[1]}</small></div></div>`).join('');
function render(){const shown=recipes.filter(r=>(active==='Tous'||r.meal===active||(active==='Favoris'&&favorites.has(r.id)))&&(`${r.name} ${r.ingredients}`.toLowerCase().includes(query)));document.querySelector('#results-count').textContent=`${shown.length} recette${shown.length>1?'s':''} à découvrir`;document.querySelector('#empty').hidden=shown.length>0;grid.innerHTML=shown.map(r=>{const c=colors[r.meal];return `<article class="recipe-card" data-id="${r.id}" tabindex="0" style="--card-bg:${c[0]};--card-accent:${c[1]}"><div class="card-art has-photo" style="background-image:linear-gradient(180deg,transparent 45%,rgba(25,40,30,.28)),url('${photoByName[r.name]}')"><button class="favorite ${favorites.has(r.id)?'saved':''}" data-favorite="${r.id}" aria-label="Ajouter aux favoris">${favorites.has(r.id)?'♥':'♡'}</button></div><div class="card-body"><div class="card-meta"><span>${r.meal}</span><span>${r.kcal} kcal</span></div><h3>${r.name}</h3><div class="macro-row"><span><strong>${r.protein} g</strong>protéines</span><span><strong>${r.carbs} g</strong>glucides</span><span><strong>${r.fat} g</strong>lipides</span></div></div></article>`}).join('');document.querySelector('#favorite-count').textContent=favorites.size}
function openRecipe(id){const r=recipes[id],steps=instructions[r.name]||[r.prep];document.querySelector('#modal-content').innerHTML=`<div class="modal-photo" style="background-image:url('${photoByName[r.name]}')"></div><div class="modal-head"><p class="eyebrow">${r.meal}</p><h2>${r.name}</h2><p>Une recette simple, nourrissante et pleine de goût.</p></div><div class="modal-macros"><div><strong>${r.kcal}</strong><small>kcal</small></div><div><strong>${r.protein} g</strong><small>protéines</small></div><div><strong>${r.carbs} g</strong><small>glucides</small></div><div><strong>${r.fat} g</strong><small>lipides</small></div></div><div class="modal-details"><div><h3>Dans ton panier</h3><ul>${r.ingredients.split(',').map(x=>`<li>${x.trim()}</li>`).join('')}</ul></div><div><h3>La préparation</h3><ol class="steps">${steps.map(x=>`<li>${x}</li>`).join('')}</ol></div></div>`;modal.showModal();document.body.classList.add('modal-open')}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');active=b.dataset.filter;render()}));
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render()});
grid.addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){e.stopPropagation();const id=+fav.dataset.favorite;favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('meal-favorites',JSON.stringify([...favorites]));render();return}const card=e.target.closest('.recipe-card');if(card)openRecipe(+card.dataset.id)});
grid.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.classList.contains('recipe-card'))openRecipe(+e.target.dataset.id)});
modal.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('close',()=>document.body.classList.remove('modal-open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.site-header nav');menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.addEventListener('click',()=>nav.classList.remove('open'));
const shaker=document.querySelector('#shaker-modal'),shakerLaunch=document.querySelector('#shaker-launch'),shakerResults=document.querySelector('#shaker-results');
function makeDay(){const breakfasts=recipes.filter(r=>r.meal==='Petit-déjeuner'),lunches=recipes.filter(r=>r.meal==='Déjeuner'),dinners=recipes.filter(r=>r.meal==='Dîner'),snacks=recipes.filter(r=>r.meal==='Collation'),days=[];for(const b of breakfasts)for(const l of lunches)for(const d of dinners)for(let mask=1;mask<(1<<snacks.length);mask++){const chosen=[b,l,d,...snacks.filter((_,i)=>mask>>i&1)],total=chosen.reduce((n,r)=>n+r.kcal,0);if(total===2900)days.push(chosen)}return days[Math.floor(Math.random()*days.length)]}
function showDay(day){const total=day.reduce((n,r)=>n+r.kcal,0),protein=day.reduce((n,r)=>n+r.protein,0);shakerResults.innerHTML=`<div class="shake-summary"><span>${day.length} recettes pour aujourd’hui</span><strong>${total.toLocaleString('fr-FR')} kcal</strong></div>${day.map((r,i)=>`<article class="shake-meal" data-shake-recipe="${r.id}" tabindex="0"><img src="${photoByName[r.name]}" alt=""><div><small>${r.meal==='Collation'?`Collation ${i-2}`:r.meal}</small><strong>${r.name}</strong></div><span>${r.kcal} kcal ›</span></article>`).join('')}<p class="shake-note">Total indicatif · ${protein} g de protéines. Clique sur une recette pour voir sa préparation.</p>`}
function shakeDay(){shaker.classList.add('is-shaking');shakerLaunch.classList.add('is-shaking');let ticks=0,preview=setInterval(()=>{showDay(makeDay());if(++ticks>5)clearInterval(preview)},110);setTimeout(()=>{clearInterval(preview);showDay(makeDay());shaker.classList.remove('is-shaking');shakerLaunch.classList.remove('is-shaking')},850)}
shakerLaunch.addEventListener('click',()=>{shaker.showModal();document.body.classList.add('modal-open');showDay(makeDay());requestAnimationFrame(shakeDay)});document.querySelector('#shake-again').addEventListener('click',shakeDay);shaker.querySelector('.shaker-close').addEventListener('click',()=>shaker.close());shaker.addEventListener('close',()=>document.body.classList.remove('modal-open'));shaker.addEventListener('click',e=>{if(e.target===shaker)shaker.close()});shakerResults.addEventListener('click',e=>{const item=e.target.closest('[data-shake-recipe]');if(item){shaker.close();openRecipe(+item.dataset.shakeRecipe)}});shakerResults.addEventListener('keydown',e=>{if(e.key==='Enter'){const item=e.target.closest('[data-shake-recipe]');if(item){shaker.close();openRecipe(+item.dataset.shakeRecipe)}}});
render();
